name: Windows Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  
jobs:
  Build-Win:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: cmd
        run: |
          pip install meson ninja
          
      - name: Download library
        shell: cmd
        run: |
          git clone --branch v0.36.0 https://github.com/mpv-player/mpv.git
          
      - name: Build library
        shell: cmd
        run: |
          cmake -B build
          cmake --build build --config Debug
          rmdir /s /q build
          cmake -B build
          cmake --build build --config Release
